# coding: utf-8

"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.article import Article

class TestArticle(unittest.TestCase):
    """Article unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Article:
        """Test Article
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Article`
        """
        model = Article()
        if include_optional:
            return Article(
                id = 1,
                title = 'Introduction to OpenAPI',
                content = 'OpenAPI helps describe REST APIs.',
                author = 'Valerii Kotsur',
                created_at = '2026-04-08T10:00Z'
            )
        else:
            return Article(
        )
        """

    def testArticle(self):
        """Test Article"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
