# coding: utf-8

"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.comment_input import CommentInput

class TestCommentInput(unittest.TestCase):
    """CommentInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentInput:
        """Test CommentInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentInput`
        """
        model = CommentInput()
        if include_optional:
            return CommentInput(
                author = 'Reader1',
                text = 'Great article'
            )
        else:
            return CommentInput(
                author = 'Reader1',
                text = 'Great article',
        )
        """

    def testCommentInput(self):
        """Test CommentInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
