# coding: utf-8

"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentsApi()

    def tearDown(self) -> None:
        pass

    def test_articles_id_comments_get(self) -> None:
        """Test case for articles_id_comments_get

        Get comments for article
        """
        pass

    def test_articles_id_comments_post(self) -> None:
        """Test case for articles_id_comments_post

        Add comment to article
        """
        pass

    def test_comments_id_delete(self) -> None:
        """Test case for comments_id_delete

        Delete comment by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
