# coding: utf-8

"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.article_input import ArticleInput

class TestArticleInput(unittest.TestCase):
    """ArticleInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArticleInput:
        """Test ArticleInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArticleInput`
        """
        model = ArticleInput()
        if include_optional:
            return ArticleInput(
                title = 'Introduction to OpenAPI',
                content = 'OpenAPI helps describe REST APIs.',
                author = 'Valerii Kotsur'
            )
        else:
            return ArticleInput(
                title = 'Introduction to OpenAPI',
                content = 'OpenAPI helps describe REST APIs.',
                author = 'Valerii Kotsur',
        )
        """

    def testArticleInput(self):
        """Test ArticleInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
