# coding: utf-8

"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.articles_api import ArticlesApi


class TestArticlesApi(unittest.TestCase):
    """ArticlesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArticlesApi()

    def tearDown(self) -> None:
        pass

    def test_articles_get(self) -> None:
        """Test case for articles_get

        Get all articles
        """
        pass

    def test_articles_id_delete(self) -> None:
        """Test case for articles_id_delete

        Delete article by ID
        """
        pass

    def test_articles_id_get(self) -> None:
        """Test case for articles_id_get

        Get article by ID
        """
        pass

    def test_articles_id_put(self) -> None:
        """Test case for articles_id_put

        Update article by ID
        """
        pass

    def test_articles_post(self) -> None:
        """Test case for articles_post

        Create a new article
        """
        pass


if __name__ == '__main__':
    unittest.main()
