# coding: utf-8

# flake8: noqa
"""
    Blog Platform API

    API for managing articles and comments

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.article import Article
from openapi_client.models.article_input import ArticleInput
from openapi_client.models.comment import Comment
from openapi_client.models.comment_input import CommentInput

